export { H2 } from './src/H2'
export { H1 } from './src/H1'
export { H3 } from './src/H3'
export { H4 } from './src/H4'
export { H5 } from './src/H5'
export { H6 } from './src/H6'
export { P } from './src/P'